// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-coffee-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-coffee-products.ts
var list_coffee_products_default = defineTool({
  name: "list_coffee_products",
  title: "List coffee products",
  description: "List the coffees currently available on the Brazilian Coffee menu, with prices.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("coffee_products").select("id, name, description, price, available").eq("available", true).order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/track-order.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
var track_order_default = defineTool2({
  name: "track_order",
  title: "Track an order",
  description: "Look up a Brazilian Coffee order by its order number and the email used at checkout, returning status, items and total.",
  inputSchema: {
    order_number: z.string().trim().describe("Order number, e.g. BC123456."),
    email: z.string().trim().describe("Email address used when the order was placed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number, email }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_order_by_number", {
      _order_number: order_number,
      _email: email
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const order = Array.isArray(data) ? data[0] : data;
    if (!order) {
      return { content: [{ type: "text", text: "No order found for that order number and email." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(order) }],
      structuredContent: { order }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the Brazilian Coffee orders belonging to the signed-in user, newest first.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("id, order_number, status, total_amount, delivery_instructions, created_at").order("created_at", { ascending: false }).limit(25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ymsqqetstluhxmrkugvg";
var mcp_default = defineMcp({
  name: "brazilian-coffee",
  title: "brazilian-coffee",
  version: "0.1.0",
  instructions: "Tools for the Brazilian Coffee delivery app. Use `list_coffee_products` for the current menu and prices, `track_order` to check an order by order number plus checkout email, and `list_my_orders` for the signed-in user's own orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_coffee_products_default, track_order_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
