// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://eticmvmetfpijbavteel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aWNtdm1ldGZwaWpiYXZ0ZWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDI2OTQsImV4cCI6MjA3MDc3ODY5NH0.h6Isaa4WG-Yi8fgonQqj3czuFzGOju0AUs3QYOX_JOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'main-auth-token', // Use unique storage key to avoid conflicts
  }
});

// Add warning detection for multiple client instances
if (typeof window !== 'undefined') {
  // Track client instances
  window.__supabaseClients = window.__supabaseClients || [];
  window.__supabaseClients.push('main-client');

  // Warn if multiple clients detected
  if (window.__supabaseClients.length > 1) {
    console.warn('⚠️ Multiple Supabase clients detected:', window.__supabaseClients);
    console.warn('This may cause authentication conflicts. Consider consolidating to a single client.');
  }
}